export async function getWeather({latitude, longitude}) {
    const generalInfo = await fetch(`https://api.weather.gov/points/${latitude},${longitude}`).then(res=>res.json())
    var data = await fetch(generalInfo.properties.forecastHourly).then(res=>res.json())
    return {...generalInfo.properties, ...data}
    // {
    //     "@context": [
    //         "https://geojson.org/geojson-ld/geojson-context.jsonld",
    //         {
    //             "@version": "1.1",
    //             wx: "https://api.weather.gov/ontology#",
    //             s: "https://schema.org/",
    //             geo: "http://www.opengis.net/ont/geosparql#",
    //             unit: "http://codes.wmo.int/common/unit/",
    //             "@vocab": "https://api.weather.gov/ontology#",
    //             geometry: { "@id": "s:GeoCoordinates", "@type": "geo:wktLiteral" },
    //             city: "s:addressLocality",
    //             state: "s:addressRegion",
    //             distance: { "@id": "s:Distance", "@type": "s:QuantitativeValue" },
    //             bearing: { "@type": "s:QuantitativeValue" },
    //             value: { "@id": "s:value" },
    //             unitCode: { "@id": "s:unitCode", "@type": "@id" },
    //             forecastOffice: { "@type": "@id" },
    //             forecastGridData: { "@type": "@id" },
    //             publicZone: { "@type": "@id" },
    //             county: { "@type": "@id" }
    //         }
    //     ],
    //     id: "https://api.weather.gov/points/30.615,-96.3379",
    //     type: "Feature",
    //     geometry: { type: "Point", coordinates: [ -96.3379, 30.615 ] },
    //     properties: {
    //         "@id": "https://api.weather.gov/points/30.615,-96.3379",
    //         "@type": "wx:Point",
    //         cwa: "HGX",
    //         forecastOffice: "https://api.weather.gov/offices/HGX",
    //         gridId: "HGX",
    //         gridX: 28,
    //         gridY: 134,
    //         forecast: "https://api.weather.gov/gridpoints/HGX/28,134/forecast",
    //         forecastHourly: "https://api.weather.gov/gridpoints/HGX/28,134/forecast/hourly",
    //         forecastGridData: "https://api.weather.gov/gridpoints/HGX/28,134",
    //         observationStations: "https://api.weather.gov/gridpoints/HGX/28,134/stations",
    //         relativeLocation: {
    //             type: "Feature",
    //             geometry: { type: "Point", coordinates: [ -96.295153, 30.585379 ] },
    //             properties: {
    //                 city: "College Station",
    //                 state: "TX",
    //                 distance: { unitCode: "wmoUnit:m", value: 5252.3724475278 },
    //                 bearing: { unitCode: "wmoUnit:degree_(angle)", value: 308 }
    //             }
    //         },
    //         forecastZone: "https://api.weather.gov/zones/forecast/TXZ196",
    //         county: "https://api.weather.gov/zones/county/TXC041",
    //         fireWeatherZone: "https://api.weather.gov/zones/fire/TXZ196",
    //         timeZone: "America/Chicago",
    //         radarStation: "KGRK"
    //     }
    // }
    
    // data = {
    //     "@context": [
    //         "https://geojson.org/geojson-ld/geojson-context.jsonld",
    //         {
    //             "@version": "1.1",
    //             wx: "https://api.weather.gov/ontology#",
    //             geo: "http://www.opengis.net/ont/geosparql#",
    //             unit: "http://codes.wmo.int/common/unit/",
    //             "@vocab": "https://api.weather.gov/ontology#"
    //         }
    //     ],
    //     type: "Feature",
    //     geometry: {
    //         type: "Polygon",
    //         coordinates: [
    //             [
    //                 [ -96.3604098, 30.6180351 ],
    //                 [ -96.3601449, 30.5953153 ],
    //                 [ -96.33373909999999, 30.5955412 ],
    //                 [ -96.33399879999999, 30.618261 ],
    //                 [ -96.3604098, 30.6180351 ]
    //             ]
    //         ]
    //     },
    //     properties: {
    //         updated: "2024-04-02T18:46:51+00:00",
    //         units: "us",
    //         forecastGenerator: "HourlyForecastGenerator",
    //         generatedAt: "2024-04-02T19:04:59+00:00",
    //         updateTime: "2024-04-02T18:46:51+00:00",
    //         validTimes: "2024-04-02T12:00:00+00:00/P8DT1H",
    //         elevation: { unitCode: "wmoUnit:m", value: 103.9368 },
    //         periods: [
    //             {
    //                 number: 1,
    //                 name: "",
    //                 startTime: "2024-04-02T14:00:00-05:00",
    //                 endTime: "2024-04-02T15:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 77,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 40 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 2,
    //                 name: "",
    //                 startTime: "2024-04-02T15:00:00-05:00",
    //                 endTime: "2024-04-02T16:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 77,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 40 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 3,
    //                 name: "",
    //                 startTime: "2024-04-02T16:00:00-05:00",
    //                 endTime: "2024-04-02T17:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 76,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 42 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 4,
    //                 name: "",
    //                 startTime: "2024-04-02T17:00:00-05:00",
    //                 endTime: "2024-04-02T18:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 73,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 9.444444444444445 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 43 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 5,
    //                 name: "",
    //                 startTime: "2024-04-02T18:00:00-05:00",
    //                 endTime: "2024-04-02T19:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 72,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 42 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/night/few,0?size=small",
    //                 shortForecast: "Mostly Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 6,
    //                 name: "",
    //                 startTime: "2024-04-02T19:00:00-05:00",
    //                 endTime: "2024-04-02T20:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 70,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.333333333333334 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 44 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/night/few,0?size=small",
    //                 shortForecast: "Mostly Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 7,
    //                 name: "",
    //                 startTime: "2024-04-02T20:00:00-05:00",
    //                 endTime: "2024-04-02T21:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 66,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.777777777777778 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 48 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/night/few,0?size=small",
    //                 shortForecast: "Mostly Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 8,
    //                 name: "",
    //                 startTime: "2024-04-02T21:00:00-05:00",
    //                 endTime: "2024-04-02T22:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 62,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.777777777777778 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 56 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/night/few,0?size=small",
    //                 shortForecast: "Mostly Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 9,
    //                 name: "",
    //                 startTime: "2024-04-02T22:00:00-05:00",
    //                 endTime: "2024-04-02T23:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 60,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.222222222222222 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 58 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/few,0?size=small",
    //                 shortForecast: "Mostly Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 10,
    //                 name: "",
    //                 startTime: "2024-04-02T23:00:00-05:00",
    //                 endTime: "2024-04-03T00:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 58,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 59 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/few,0?size=small",
    //                 shortForecast: "Mostly Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 11,
    //                 name: "",
    //                 startTime: "2024-04-03T00:00:00-05:00",
    //                 endTime: "2024-04-03T01:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 56,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.111111111111111 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 62 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 12,
    //                 name: "",
    //                 startTime: "2024-04-03T01:00:00-05:00",
    //                 endTime: "2024-04-03T02:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 55,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.111111111111111 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 64 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 13,
    //                 name: "",
    //                 startTime: "2024-04-03T02:00:00-05:00",
    //                 endTime: "2024-04-03T03:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 53,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.111111111111111 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 69 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 14,
    //                 name: "",
    //                 startTime: "2024-04-03T03:00:00-05:00",
    //                 endTime: "2024-04-03T04:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 51,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 71 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 15,
    //                 name: "",
    //                 startTime: "2024-04-03T04:00:00-05:00",
    //                 endTime: "2024-04-03T05:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 50,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 74 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 16,
    //                 name: "",
    //                 startTime: "2024-04-03T05:00:00-05:00",
    //                 endTime: "2024-04-03T06:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 48,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 80 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 17,
    //                 name: "",
    //                 startTime: "2024-04-03T06:00:00-05:00",
    //                 endTime: "2024-04-03T07:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 47,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 79 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 18,
    //                 name: "",
    //                 startTime: "2024-04-03T07:00:00-05:00",
    //                 endTime: "2024-04-03T08:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 46,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 86 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 19,
    //                 name: "",
    //                 startTime: "2024-04-03T08:00:00-05:00",
    //                 endTime: "2024-04-03T09:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 47,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 83 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 20,
    //                 name: "",
    //                 startTime: "2024-04-03T09:00:00-05:00",
    //                 endTime: "2024-04-03T10:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 53,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 71 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 21,
    //                 name: "",
    //                 startTime: "2024-04-03T10:00:00-05:00",
    //                 endTime: "2024-04-03T11:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 59,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.222222222222222 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 60 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 22,
    //                 name: "",
    //                 startTime: "2024-04-03T11:00:00-05:00",
    //                 endTime: "2024-04-03T12:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 64,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 48 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 23,
    //                 name: "",
    //                 startTime: "2024-04-03T12:00:00-05:00",
    //                 endTime: "2024-04-03T13:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 67,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 40 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 24,
    //                 name: "",
    //                 startTime: "2024-04-03T13:00:00-05:00",
    //                 endTime: "2024-04-03T14:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 70,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 36 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 25,
    //                 name: "",
    //                 startTime: "2024-04-03T14:00:00-05:00",
    //                 endTime: "2024-04-03T15:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 72,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 33 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 26,
    //                 name: "",
    //                 startTime: "2024-04-03T15:00:00-05:00",
    //                 endTime: "2024-04-03T16:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 74,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 30 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 27,
    //                 name: "",
    //                 startTime: "2024-04-03T16:00:00-05:00",
    //                 endTime: "2024-04-03T17:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 75,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 31 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 28,
    //                 name: "",
    //                 startTime: "2024-04-03T17:00:00-05:00",
    //                 endTime: "2024-04-03T18:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 75,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.111111111111111 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 32 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 29,
    //                 name: "",
    //                 startTime: "2024-04-03T18:00:00-05:00",
    //                 endTime: "2024-04-03T19:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 74,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 34 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 30,
    //                 name: "",
    //                 startTime: "2024-04-03T19:00:00-05:00",
    //                 endTime: "2024-04-03T20:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 71,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.777777777777778 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 41 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 31,
    //                 name: "",
    //                 startTime: "2024-04-03T20:00:00-05:00",
    //                 endTime: "2024-04-03T21:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 67,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.222222222222222 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 45 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 32,
    //                 name: "",
    //                 startTime: "2024-04-03T21:00:00-05:00",
    //                 endTime: "2024-04-03T22:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 64,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.222222222222222 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 50 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 33,
    //                 name: "",
    //                 startTime: "2024-04-03T22:00:00-05:00",
    //                 endTime: "2024-04-03T23:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 61,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 53 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 34,
    //                 name: "",
    //                 startTime: "2024-04-03T23:00:00-05:00",
    //                 endTime: "2024-04-04T00:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 59,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 57 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "N",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 35,
    //                 name: "",
    //                 startTime: "2024-04-04T00:00:00-05:00",
    //                 endTime: "2024-04-04T01:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 57,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 62 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 36,
    //                 name: "",
    //                 startTime: "2024-04-04T01:00:00-05:00",
    //                 endTime: "2024-04-04T02:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 56,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 64 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SW",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 37,
    //                 name: "",
    //                 startTime: "2024-04-04T02:00:00-05:00",
    //                 endTime: "2024-04-04T03:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 54,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 69 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SW",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 38,
    //                 name: "",
    //                 startTime: "2024-04-04T03:00:00-05:00",
    //                 endTime: "2024-04-04T04:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 53,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 71 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SW",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 39,
    //                 name: "",
    //                 startTime: "2024-04-04T04:00:00-05:00",
    //                 endTime: "2024-04-04T05:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 52,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.111111111111111 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 71 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SW",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 40,
    //                 name: "",
    //                 startTime: "2024-04-04T05:00:00-05:00",
    //                 endTime: "2024-04-04T06:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 50,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 74 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SW",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 41,
    //                 name: "",
    //                 startTime: "2024-04-04T06:00:00-05:00",
    //                 endTime: "2024-04-04T07:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 49,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 5.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 77 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 42,
    //                 name: "",
    //                 startTime: "2024-04-04T07:00:00-05:00",
    //                 endTime: "2024-04-04T08:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 50,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 6.666666666666667 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 80 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 43,
    //                 name: "",
    //                 startTime: "2024-04-04T08:00:00-05:00",
    //                 endTime: "2024-04-04T09:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 53,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.222222222222222 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 74 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 44,
    //                 name: "",
    //                 startTime: "2024-04-04T09:00:00-05:00",
    //                 endTime: "2024-04-04T10:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 58,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.777777777777778 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 64 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 45,
    //                 name: "",
    //                 startTime: "2024-04-04T10:00:00-05:00",
    //                 endTime: "2024-04-04T11:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 63,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.333333333333334 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 56 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 46,
    //                 name: "",
    //                 startTime: "2024-04-04T11:00:00-05:00",
    //                 endTime: "2024-04-04T12:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 68,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.333333333333334 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 47 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 47,
    //                 name: "",
    //                 startTime: "2024-04-04T12:00:00-05:00",
    //                 endTime: "2024-04-04T13:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 72,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.333333333333334 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 40 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 48,
    //                 name: "",
    //                 startTime: "2024-04-04T13:00:00-05:00",
    //                 endTime: "2024-04-04T14:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 76,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.333333333333334 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 36 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 49,
    //                 name: "",
    //                 startTime: "2024-04-04T14:00:00-05:00",
    //                 endTime: "2024-04-04T15:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 78,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.777777777777778 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 32 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "W",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 50,
    //                 name: "",
    //                 startTime: "2024-04-04T15:00:00-05:00",
    //                 endTime: "2024-04-04T16:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 80,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.222222222222222 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 29 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 51,
    //                 name: "",
    //                 startTime: "2024-04-04T16:00:00-05:00",
    //                 endTime: "2024-04-04T17:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 80,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 7.777777777777778 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 30 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 52,
    //                 name: "",
    //                 startTime: "2024-04-04T17:00:00-05:00",
    //                 endTime: "2024-04-04T18:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 80,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 32 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "NW",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 53,
    //                 name: "",
    //                 startTime: "2024-04-04T18:00:00-05:00",
    //                 endTime: "2024-04-04T19:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 80,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 37 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "NE",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 54,
    //                 name: "",
    //                 startTime: "2024-04-04T19:00:00-05:00",
    //                 endTime: "2024-04-04T20:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 78,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 11.666666666666666 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 42 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "E",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 55,
    //                 name: "",
    //                 startTime: "2024-04-04T20:00:00-05:00",
    //                 endTime: "2024-04-04T21:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 74,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 11.666666666666666 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 47 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "E",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 56,
    //                 name: "",
    //                 startTime: "2024-04-04T21:00:00-05:00",
    //                 endTime: "2024-04-04T22:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 70,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 11.11111111111111 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 53 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "E",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 57,
    //                 name: "",
    //                 startTime: "2024-04-04T22:00:00-05:00",
    //                 endTime: "2024-04-04T23:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 66,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 58 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "E",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 58,
    //                 name: "",
    //                 startTime: "2024-04-04T23:00:00-05:00",
    //                 endTime: "2024-04-05T00:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 64,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 61 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 59,
    //                 name: "",
    //                 startTime: "2024-04-05T00:00:00-05:00",
    //                 endTime: "2024-04-05T01:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 62,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 64 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 60,
    //                 name: "",
    //                 startTime: "2024-04-05T01:00:00-05:00",
    //                 endTime: "2024-04-05T02:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 61,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 67 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 61,
    //                 name: "",
    //                 startTime: "2024-04-05T02:00:00-05:00",
    //                 endTime: "2024-04-05T03:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 59,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 72 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 62,
    //                 name: "",
    //                 startTime: "2024-04-05T03:00:00-05:00",
    //                 endTime: "2024-04-05T04:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 57,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 9.444444444444445 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 75 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 63,
    //                 name: "",
    //                 startTime: "2024-04-05T04:00:00-05:00",
    //                 endTime: "2024-04-05T05:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 55,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 77 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 64,
    //                 name: "",
    //                 startTime: "2024-04-05T05:00:00-05:00",
    //                 endTime: "2024-04-05T06:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 53,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 82 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/skc,0?size=small",
    //                 shortForecast: "Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 65,
    //                 name: "",
    //                 startTime: "2024-04-05T06:00:00-05:00",
    //                 endTime: "2024-04-05T07:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 52,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 85 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 66,
    //                 name: "",
    //                 startTime: "2024-04-05T07:00:00-05:00",
    //                 endTime: "2024-04-05T08:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 53,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 83 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 67,
    //                 name: "",
    //                 startTime: "2024-04-05T08:00:00-05:00",
    //                 endTime: "2024-04-05T09:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 56,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 75 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 68,
    //                 name: "",
    //                 startTime: "2024-04-05T09:00:00-05:00",
    //                 endTime: "2024-04-05T10:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 60,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 64 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 69,
    //                 name: "",
    //                 startTime: "2024-04-05T10:00:00-05:00",
    //                 endTime: "2024-04-05T11:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 65,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 8.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 54 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 70,
    //                 name: "",
    //                 startTime: "2024-04-05T11:00:00-05:00",
    //                 endTime: "2024-04-05T12:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 69,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 9.444444444444445 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 48 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/skc,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 71,
    //                 name: "",
    //                 startTime: "2024-04-05T12:00:00-05:00",
    //                 endTime: "2024-04-05T13:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 74,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 9.444444444444445 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 42 },
    //                 windSpeed: "5 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 72,
    //                 name: "",
    //                 startTime: "2024-04-05T13:00:00-05:00",
    //                 endTime: "2024-04-05T14:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 77,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 39 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 73,
    //                 name: "",
    //                 startTime: "2024-04-05T14:00:00-05:00",
    //                 endTime: "2024-04-05T15:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 79,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 37 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 74,
    //                 name: "",
    //                 startTime: "2024-04-05T15:00:00-05:00",
    //                 endTime: "2024-04-05T16:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 81,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 10.555555555555555 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 36 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 75,
    //                 name: "",
    //                 startTime: "2024-04-05T16:00:00-05:00",
    //                 endTime: "2024-04-05T17:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 81,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 11.11111111111111 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 37 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 76,
    //                 name: "",
    //                 startTime: "2024-04-05T17:00:00-05:00",
    //                 endTime: "2024-04-05T18:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 81,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 11.666666666666666 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 38 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/few,0?size=small",
    //                 shortForecast: "Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 77,
    //                 name: "",
    //                 startTime: "2024-04-05T18:00:00-05:00",
    //                 endTime: "2024-04-05T19:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 81,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 12.222222222222221 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 40 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/few,0?size=small",
    //                 shortForecast: "Mostly Clear",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 78,
    //                 name: "",
    //                 startTime: "2024-04-05T19:00:00-05:00",
    //                 endTime: "2024-04-05T20:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 79,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 12.777777777777779 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 44 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/sct,0?size=small",
    //                 shortForecast: "Partly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 79,
    //                 name: "",
    //                 startTime: "2024-04-05T20:00:00-05:00",
    //                 endTime: "2024-04-05T21:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 76,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 12.777777777777779 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 49 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/sct,0?size=small",
    //                 shortForecast: "Partly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 80,
    //                 name: "",
    //                 startTime: "2024-04-05T21:00:00-05:00",
    //                 endTime: "2024-04-05T22:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 72,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 12.777777777777779 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 56 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/night/sct,0?size=small",
    //                 shortForecast: "Partly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 81,
    //                 name: "",
    //                 startTime: "2024-04-05T22:00:00-05:00",
    //                 endTime: "2024-04-05T23:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 68,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 12.222222222222221 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 61 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/night/sct,0?size=small",
    //                 shortForecast: "Partly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 82,
    //                 name: "",
    //                 startTime: "2024-04-05T23:00:00-05:00",
    //                 endTime: "2024-04-06T00:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 66,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 12.222222222222221 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 65 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/night/sct,0?size=small",
    //                 shortForecast: "Partly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 83,
    //                 name: "",
    //                 startTime: "2024-04-06T00:00:00-05:00",
    //                 endTime: "2024-04-06T01:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 65,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 12.777777777777779 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 70 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/night/sct,0?size=small",
    //                 shortForecast: "Partly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 84,
    //                 name: "",
    //                 startTime: "2024-04-06T01:00:00-05:00",
    //                 endTime: "2024-04-06T02:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 64,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 12.777777777777779 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 73 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/night/sct,0?size=small",
    //                 shortForecast: "Partly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 85,
    //                 name: "",
    //                 startTime: "2024-04-06T02:00:00-05:00",
    //                 endTime: "2024-04-06T03:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 63,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 13.333333333333334 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 78 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/night/sct,0?size=small",
    //                 shortForecast: "Partly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 86,
    //                 name: "",
    //                 startTime: "2024-04-06T03:00:00-05:00",
    //                 endTime: "2024-04-06T04:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 62,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 13.333333333333334 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 81 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/night/sct,0?size=small",
    //                 shortForecast: "Partly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 87,
    //                 name: "",
    //                 startTime: "2024-04-06T04:00:00-05:00",
    //                 endTime: "2024-04-06T05:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 61,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 13.88888888888889 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 87 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/bkn,0?size=small",
    //                 shortForecast: "Mostly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 88,
    //                 name: "",
    //                 startTime: "2024-04-06T05:00:00-05:00",
    //                 endTime: "2024-04-06T06:00:00-05:00",
    //                 isDaytime: false,
    //                 temperature: 60,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 14.444444444444445 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 93 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/night/bkn,0?size=small",
    //                 shortForecast: "Mostly Cloudy",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 89,
    //                 name: "",
    //                 startTime: "2024-04-06T06:00:00-05:00",
    //                 endTime: "2024-04-06T07:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 59,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 14.444444444444445 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 95 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 90,
    //                 name: "",
    //                 startTime: "2024-04-06T07:00:00-05:00",
    //                 endTime: "2024-04-06T08:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 60,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 15 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 96 },
    //                 windSpeed: "10 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 91,
    //                 name: "",
    //                 startTime: "2024-04-06T08:00:00-05:00",
    //                 endTime: "2024-04-06T09:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 62,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 15 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 89 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 92,
    //                 name: "",
    //                 startTime: "2024-04-06T09:00:00-05:00",
    //                 endTime: "2024-04-06T10:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 66,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 15 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 79 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 93,
    //                 name: "",
    //                 startTime: "2024-04-06T10:00:00-05:00",
    //                 endTime: "2024-04-06T11:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 69,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 15 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 70 },
    //                 windSpeed: "15 mph",
    //                 windDirection: "SE",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 94,
    //                 name: "",
    //                 startTime: "2024-04-06T11:00:00-05:00",
    //                 endTime: "2024-04-06T12:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 72,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 15 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 63 },
    //                 windSpeed: "20 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 95,
    //                 name: "",
    //                 startTime: "2024-04-06T12:00:00-05:00",
    //                 endTime: "2024-04-06T13:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 75,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 15 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 58 },
    //                 windSpeed: "20 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 96,
    //                 name: "",
    //                 startTime: "2024-04-06T13:00:00-05:00",
    //                 endTime: "2024-04-06T14:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 77,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 15 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 54 },
    //                 windSpeed: "20 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 97,
    //                 name: "",
    //                 startTime: "2024-04-06T14:00:00-05:00",
    //                 endTime: "2024-04-06T15:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 78,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 14.444444444444445 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 49 },
    //                 windSpeed: "20 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 98,
    //                 name: "",
    //                 startTime: "2024-04-06T15:00:00-05:00",
    //                 endTime: "2024-04-06T16:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 79,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 14.444444444444445 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 48 },
    //                 windSpeed: "20 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 99,
    //                 name: "",
    //                 startTime: "2024-04-06T16:00:00-05:00",
    //                 endTime: "2024-04-06T17:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 79,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 14.444444444444445 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 49 },
    //                 windSpeed: "20 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             {
    //                 number: 100,
    //                 name: "",
    //                 startTime: "2024-04-06T17:00:00-05:00",
    //                 endTime: "2024-04-06T18:00:00-05:00",
    //                 isDaytime: true,
    //                 temperature: 78,
    //                 temperatureUnit: "F",
    //                 temperatureTrend: null,
    //                 probabilityOfPrecipitation: { unitCode: "wmoUnit:percent", value: 0 },
    //                 dewpoint: { unitCode: "wmoUnit:degC", value: 15 },
    //                 relativeHumidity: { unitCode: "wmoUnit:percent", value: 52 },
    //                 windSpeed: "20 mph",
    //                 windDirection: "S",
    //                 icon: "https://api.weather.gov/icons/land/day/bkn,0?size=small",
    //                 shortForecast: "Partly Sunny",
    //                 detailedForecast: ""
    //             },
    //             ... 56 more items
    //         ]
    //     }
    // }
}